### ISSUE TITLE
no ability to pass kwargs to create_engine

### ISSUE THREAD

**Issue by jacob-r-g** [felipeam86/cachesql#5]
Hello! Love your library and use it often in my daily work.

One feature I would love to see is very simply adding kwargs to the Database class that can be passed to the sqlalchemy create_engine method. Here is a possible  implementation:

```
...
    def __init__(
        self,
        uri: str,
        name: str = None,
        cache_store: Union[str, Path, store.BaseStore] = None,
        store_backend: str = "parquet",
        normalize: bool = True,
        compression: Any = None,
        **kwargs
    ):
        self.__dict__.update(**kwargs)
        self.kwargs = kwargs
        self.engine = create_engine(uri, **self.kwargs)
...
```

I think there are a number of uses for this, but I can provide my primary use case: In order to connect to my company's database I need to be attached to the VPN. If I am not attached to the VPN, it takes many minutes for sqlalchemy to raise an error which is a frustrating waste of time. However, if I pass a more reasonable timeout to the `create_engine` method like this:

```
engine = sqlalchemy.create_engine(
           uri='MY_URI',
            connect_args={"connect_timeout": 5},
        )
```
then an error is quickly raised, indicating I need to check my VPN connection then retry the query.

Let me know what you think. Thanks again  @felipeam86 for publishing such a neat, and useful little library! If you are open to collaborating, I am happy to make the code changes and submit a PR myself :)

**Comment by felipeam86** [comment]
Hi @jacob-r-g !

Thanks for the kind words. Nice to see other people benefiting from this package! What you are proposing makes sense.

I will be very glad to collaborate with you. Please submit a PR and I'll process!

**Comment by jacob-r-g** [comment]
I would be happy to, but it looks like i do not have write access to the repository to publish a branch or submit a PR. Can you provide access @felipeam86 ?

**Comment by felipeam86** [comment]
@jacob-r-g I don't think you need to be a collaborator. You can fork the repository and do a PR from it.

In any case, I did add you as a collaborator to the project to make things simpler

**Comment by jacob-r-g** [comment]
Sounds good, I have opened a PR

**Comment by felipeam86** [comment]
@jacob-r-g I've done a new release with your pull request. I'll close this issue. Feel free to open a new one if it doesn't work
